name: mapvisualization
namespace: default

web:
  - name: map-viz-service
    path: /
    port:
      - 5000
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"

switch:
  web_ssl: off
